
version: "3.7"

services:

  web:

    container_name: backend

    build: ./CoreWebApplication2/CoreWebApplication2/Dockerfile

    depends_on:

      - db



  db:

    image: postgres

    container_name: postgres
