
name: continue on error
on: push

jobs:

  job1:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
      
    - run: make package-commit_hash-artifacts-for-deploy
      continue-on-error: true
      
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
