name: create tag/release

on: 
  push

jobs:

  job1:
    name: create tag/release

    runs-on: ubuntu-latest    

    steps:

    - uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: refs/tags/v1.5

        release_name: Release refs/tags/v1.5

        body: |

            Changes in this Release

            - First Change

            - Second Change

        draft: false

        prerelease: false
