name: create tag/release

on: check_run
  #push:
    #branches:
      #- master
jobs:

  job1:
    name: create tag/release

    runs-on: ubuntu-latest    

    steps:

    - uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ADDTAG_PAT }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: refs/tags/v1.6

        release_name: Release refs/tags/v1.6

        body: |

            Changes in this Release

            - First Change

            - Second Change

        draft: false

        prerelease: false
