name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release CoreWebApplication1/CoreWebApplication1.sln
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: For Test
        path: CoreWebApplication1
   
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: For Test
    
      - run: cat For Test
   
