name: create error
on: push

jobs:
  job1:
    if: github.event.commits.message == *"[SKIP CI]"*
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
      with:
          repository: Yanjingzhu/privateone 
          token: ${{secrets.GITHUB_PAT}}
          ref: master    
          #- uses: maddox/actions/sleep@master
          # dddd  
