name: check out other repo
on: 
  push: 
    tags: 
      - '*'

jobs:
  job1:
    #if: contains(github.event.commits[0].message,'[SKIP CI]') != true 
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_COMMIT: ${{ toJson(github.event.commits[0].message) }}
      run: echo "$GITHUB_COMMIT"
    - uses: actions/checkout@master
      #with:
          #repository: Yanjingzhu/privateone 
          #token: ${{secrets.GITHUB_PAT}}
          #ref: master    
          
          #- uses: maddox/actions/sleep@master
          # dddd tt 
          # ddddxxx
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false
