name: create error
on: push

jobs:
  job1:
    if: github.event.commits[0].message != '*[SKIP CI]*'
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_COMMIT: ${{ toJson(github.event.commits[0].message) }}
      run: echo "$GITHUB_COMMIT"
    - uses: actions/checkout@master
      with:
          repository: Yanjingzhu/privateone 
          token: ${{secrets.GITHUB_PAT}}
          ref: master    
          #- uses: maddox/actions/sleep@master
          # dddd tt 
          # dddd
