name: test status event
on: push

jobs:
  job1:
    #if: contains(github.event.commits[0].message,'[SKIP CI]') != true 
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - run: echo $ORG
      env:
        ORG: ${{ secrets.ORG_Secret1 }}
