name: create error
on: pull_request

jobs:
  job1:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0  
      
    #- uses: maddox/actions/sleep@master
