name: create error
on: push

jobs:
  job1:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
      with:
          repository: Yanjingzhu/YanGitRepo
          token: de9393a15a2d70e4e1ad77f713b27c236051aa3d
    #- uses: maddox/actions/sleep@master
