name: test status event
on: status

jobs:
  job1:
    #if: contains(github.event.commits[0].message,'[SKIP CI]') != true 
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
      
    - name: Dump GitHub context
      env:
          GITHUB: ${{ toJson(github) }}
      run: echo "$GITHUB"
    - uses: actions/checkout@master
      #with:
          #repository: Yanjingzhu/privateone 
          #token: ${{secrets.GITHUB_PAT}}
          #ref: master    
          
          #- uses: maddox/actions/sleep@master
          # dddd tt 
          # ddddxxx
   
