name: create error
on: push

jobs:
  job1:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
      with:
          repository: Yanjingzhu/YanGitRepo
          token: ${{secrets.GITHUB_TOKEN}}
    #- uses: maddox/actions/sleep@master
