name: test status event
on: status

jobs:
  job1:
    #if: contains(github.event.commits[0].message,'[SKIP CI]') != true 
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_COMMIT: ${{ toJson(github.event.commits[0].message) }}
      run: echo "$GITHUB_COMMIT"
    - uses: actions/checkout@master
      #with:
          #repository: Yanjingzhu/privateone 
          #token: ${{secrets.GITHUB_PAT}}
          #ref: master    
          
          #- uses: maddox/actions/sleep@master
          # dddd tt 
          # ddddxxx
   
